# Generated by Django 6.0.5 on 2026-05-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='voyages/')),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('date_retour', models.DateField(verbose_name='Date de retour')),
                ('prix_par_personne', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix par personne (F CFA)')),
                ('places_total', models.PositiveIntegerField(verbose_name='Nombre de places total')),
                ('places_disponibles', models.PositiveIntegerField(verbose_name='Places disponibles')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('complet', 'Complet'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='disponible', max_length=15, verbose_name='Statut')),
                ('inclus', models.TextField(blank=True, help_text='Vol, hôtel, repas... (un élément par ligne)', verbose_name='Ce qui est inclus')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='destinations.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'ordering': ['date_depart'],
            },
        ),
    ]
