# Generated by Django 6.0.5 on 2026-05-24 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voyages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('nb_personnes', models.PositiveIntegerField(default=1, verbose_name='Nombre de personnes')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total (F CFA)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiel'), ('complet', 'Complet'), ('rembourse', 'Remboursé')], default='non_paye', max_length=15, verbose_name='Statut paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Agent responsable')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voyages.voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
